//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int idfriend1 { get; set; }
        public int idfriend2 { get; set; }
        public Nullable<System.DateTime> reqdate { get; set; }
        public Nullable<System.DateTime> friendshipdate { get; set; }
        public Nullable<bool> done { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
