//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int idpost { get; set; }
        public int iduser { get; set; }
        public string text { get; set; }
        public byte[] image { get; set; }
        public System.DateTime datepost { get; set; }
        public System.TimeSpan timepost { get; set; }
        public int type { get; set; }
    
        public virtual User User { get; set; }
    }
}
